spring.application.name=ems-new
spring.datasource.url=jdbc:postgresql://localhost:5432/ems_db
spring.datasource.username=emsuser
spring.datasource.password=emspass
spring.jpa.hibernate.ddl-auto=create
spring.flyway.locations=classpath:/db/migration
spring.output.ansi.enabled=always
spring.jpa.show-sql=true
